const data = [
  { label: "AUD", value: "AUD" },
  { label: "BRL", value: "BRL" },
  { label: "CAD", value: "CAD" },
  { label: "CNY", value: "CNY" },
  { label: "CZK", value: "CZK" },
  { label: "DKK", value: "DKK" },
  { label: "EUR", value: "EUR" },
  { label: "HKD", value: "HKD" },
  { label: "HUF", value: "HUF" },
  { label: "ILS", value: "ILS" },
  { label: "JPY", value: "JPY" },
  { label: "MYR", value: "MYR" },
  { label: "MXN", value: "MXN" },
  { label: "TWD", value: "TWD" },
  { label: "NZD", value: "NZD" },
  { label: "NOK", value: "NOK" },
  { label: "PHP", value: "PHP" },
  { label: "PLN", value: "PLN" },
  { label: "GBP", value: "GBP" },
  { label: "SGD", value: "SGD" },
  { label: "SEK", value: "SEK" },
  { label: "CHF", value: "CHF" },
  { label: "THB", value: "THB" },
  { label: "USD", value: "USD" },
];

export default data;
