export enum SCREENS {
  "HOME" = "/",
  "SALARY_HIKE_PERCENTAGE_CALCULATOR" = "/tools/salary-hike-percentage-calculator",
  "STRING_TO_ASCII" = "/tools/string-to-ascii",
  "ASCII_TO_STRING" = "/tools/ascii-to-string",
  "JSON_TO_STRING" = "/tools/json-to-string",
  "JSON_PARSER" = "/tools/json-parser",
  "JSON_MINIFIER" = "/tools/secure-reliable-json-minifier-compressor",
  "TEXT_TO_UPPERCASE" = "/tools/text-to-uppercase",
  "TEXT_TO_LOWERCASE" = "/tools/text-to-lowercase",
  "WORD_COUNTER" = "/tools/word-counter",
  "REPLACE_SPACES" = "/tools/replace-spaces",
  "REMOVE_SPACES" = "/texttools/remove-spaces",
  "REMOVE_EXTRA_SPACES" = "/texttools/remove-extra-spaces",
  "URL_DECODE" = "/tools/url-decode",
  "URL_ENCODE" = "/tools/url-encode",
  "TOOLS" = "/tools",
  "UUID_GENERATOR" = "/tools/uuid-generator",
  "JSON_DIFF" = "/tools/diff/json-diff-compare",
}
